[package]
name = "rust_advent_of_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
reqwest = "0.11.7"
tokio = { version = "1.14.0", features = ["full"] }
crate = "*"